meta_product_name: "Chez Gaullot"
meta_title: "Chez Gaullot"
meta_description: "Si t'es pas content, t'as qu'à aller manger chez Gaullot!"
meta_image: "chez-gaullot-main-og-min.jpg" # should exist in `app/assets/images/`
